version: "3.9"
services:

  ecomm:
    build: .
    container_name: ecomm-app
    networks:
      - ecomm-mongo
    ports:
      - 3000:3000
    depends_on:
      - mongo-ecomm
    environment:
      HOST_MONGO: mongo-ecomm

  mongo-ecomm:
    image: mongo
    container_name: mongo-ecomm
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - db-mongo-ecomm:/data/db
      - type: bind
        source: ./mongo
        target: /mongo-scripts
    restart: always
    ports:
      - 27017:27017
    networks:
      - ecomm-mongo

networks:
  ecomm-mongo:
    driver: bridge

volumes:
  db-mongo-ecomm:
    name: db-mongo-ecomm
