openapi: 3.0.1


info:
  title: Ecomm - LevelUp Alura
  description: API para e-commerce desenvolvida durante o programa LevelUp da Alura com a PagoNxt
  version: 0.0.1
  contact:
    name: Filipe Garrote
    email: filipe.garrote@gmail.com
    
    
servers:
- url: http://localhost:3000/
  description: API - Ecomm
  
  
paths:

  /api/categories:
    get:
      summary: Realiza a listagem de todas as categorias
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                minLength: 0
                type: array
                items:
                  $ref: "#/components/schemas/CategoriaComID"
                  
  /api/admin/categories:
    post:
      summary: Realiza a inserção de uma nova categoria
      requestBody:
        content:
            application/json:
              schema:
                $ref: "#/components/schemas/NovaCategoria"
      responses:
        201:
          description: Criado
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/CategoriaComID"

                  
  /categories/{id}:
    parameters: 
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Realiza a listagem de uma categoria específica
      responses:
        200:
          $ref: "#/components/responses/CategoriaSucesso"
        404:
          $ref: "#/components/responses/NotFound"
            
            
  /api/admin/categories/{id}:
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer 
    put:
      summary: Realiza a alteração dos dados de uma categoria
      requestBody:
        content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  status:
                    type: string
      responses:
        200:
          $ref: "#/components/responses/CategoriaSucesso"
        404:
          $ref: "#/components/responses/NotFound"
          
    delete:
      summary: Realiza a exclusão de uma categoria
      responses:
        200:
          description: Categoria deletada
        404:
          $ref: "#/components/responses/NotFound"
    
  /api/admin/categories/ativacao/{id}:
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    patch:
      summary: Realiza a ativação de uma categoria
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  status:
                    type: string
                    enum: 
                    - "ATIVA"
        404:
          $ref: "#/components/responses/NotFound"
          
          
  /api/admin/products:
    post:
      summary: Realiza a inserção de um novo produto
      requestBody:
        content:
            application/json:
              schema:
                $ref: "#/components/schemas/NovoProduto"
      responses:
        201:
          description: Criado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProdutoComID"
                
  /api/products:
    get:
      summary: Lista todos os produtos existentes
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                minLength: 0
                items:
                  $ref: "#/components/schemas/ProdutoComID"
                  
  
  /api/products/{id}:
    parameters:
    - name: id
      required: true
      in: path
      schema:
        type: integer
    
    get:
      summary: Lista um produto específico
      responses:
        200:
          $ref: "#/components/responses/ProdutoSucesso"
        404:
          $ref: "#/components/responses/NotFound"
          
          
  /api/admin/products/{id}:
    parameters:
    - name: id
      required: true
      in: path
      schema:
        type: integer
    
    put:
      summary: Atualiza um produto específico
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NovoProduto"
      responses:
        200:
          $ref: "#/components/responses/ProdutoSucesso"
        404:
          $ref: "#/components/responses/NotFound"
          
    delete:
      summary: Exclui um produto específico
      responses:
        200:
          description: Produto deletado
        404:
          $ref: "#/components/responses/NotFound"
          
          
components:
  schemas:
    CategoriaComID:
      description: "entidade categoria"
      type: object
      properties:
        id: 
          type: integer
        nome:
          type: string
        status:
          type: string
          
    NovaCategoria:
      description: "nova categoria"
      type: object
      properties:
        nome:
          type: string
          
    NovoProduto:
      description: "novo produto"
      type: object
      properties:
        nome:
          type: string
        descricao:
          type: string
        slug:
          type: string
        precoUnitario:
          type: decimal
        quantidadeEmEstoque:
          type: integer
        categoria:
          type: string
    
    ProdutoComID:
      description: "produto"
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        descricao:
          type: string
        slug:
          type: string
        precoUnitario:
          type: decimal
        quantidadeEmEstoque:
          type: integer
        categoria:
          type: string
        
          
  responses:
    NotFound:
      description: Não Encontrado
      content:
        application/json:
          example: "Not Found"
      
    CategoriaSucesso:
      description: Sucesso
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CategoriaComID"
    
    ProdutoSucesso:
      description: Sucesso
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProdutoComID"