openapi: 3.0.1
info:
  title: Ecomm - LevelUp Alura
  description: API para e-commerce desenvolvida durante o programa LevelUp da Alura com a PagoNxt
  version: 0.0.1
  contact:
    name: Filipe Garrote
    email: filipe.garrote@gmail.com
servers:
- url: http://localhost:3000/
  description: API - Ecomm
paths:
  /categories:
    get:
      summary: Realiza a listagem de todas as categorias
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Categoria"
          
components:
  schemas:
    Categoria:
      description: "categoria"
      type: object
      properties:
        id: 
          type: integer
        nome:
          type: string
        status:
          type: string
