openapi: 3.0.1


info:
  title: Ecomm - LevelUp Alura
  description: API para e-commerce desenvolvida durante o programa LevelUp da Alura com a PagoNxt
  version: 0.0.1
  contact:
    name: Filipe Garrote
    email: filipe.garrote@gmail.com
    
    
servers:
- url: http://localhost:3000/
  description: API - Ecomm
  
  
paths:

  /api/categories:
    get:
      summary: Realiza a listagem de todas as categorias
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                minLength: 0
                type: array
                items:
                  $ref: "#/components/schemas/CategoriaComID"
                  
  /api/admin/categories:
    post:
      summary: Realiza a inserção de uma nova categoria
      requestBody:
        content:
            application/json:
              schema:
                $ref: "#/components/schemas/NovaCategoria"
      responses:
        201:
          description: Criado
          content:
            application/json:
              schema:
                minLength: 0
                type: array
                items:
                  $ref: "#/components/schemas/CategoriaComID"
                  
  /categories/{id}:
    parameters: 
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Realiza a listagem de uma categoria específica
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoriaComID"
        404:
          $ref: "#/components/responses/NotFound"
            

          
          
components:
  schemas:
    CategoriaComID:
      description: "entidade categoria"
      type: object
      properties:
        id: 
          type: integer
        nome:
          type: string
        status:
          type: string
          
    NovaCategoria:
      description: "nova categoria"
      type: object
      properties:
        nome:
          type: string
          
  responses:
    NotFound:
      description: Não Encontrado
      content:
        application/json:
          example: "Not Found"
      
